import Foundation
import MLX
import MLXLMCommon
import MLXVLM
import XCTest

/// Tests for Pixtral/Mistral3 message generation to verify mistral-common compatibility
///
/// These tests ensure that the message format generated by PixtralMessageGenerator
/// matches the expected mistral-common protocol structure for UserMessage, AssistantMessage, etc.
///
/// Reference: mistral-common/src/mistral_common/protocol/instruct/messages.py
public class PixtralMessageGeneratorTests: XCTestCase {

    // MARK: - Text-Only Messages

    public func testSimpleTextMessage() {
        let chat: [Chat.Message] = [
            .user("Tell me a story.")
        ]

        let userInput = UserInput(chat: chat)
        let messages = PixtralMessageGenerator().generate(from: userInput)

        let expected = [
            [
                "role": "user",
                "content": "Tell me a story.",
            ]
        ]

        assertEqual(expected, messages)
    }

    public func testMultiTurnConversation() {
        let chat: [Chat.Message] = [
            .system("You are a helpful assistant."),
            .user("What is MLX?"),
            .assistant("MLX is a machine learning framework for Apple silicon."),
            .user("Tell me more."),
        ]

        let userInput = UserInput(chat: chat)
        let messages = PixtralMessageGenerator().generate(from: userInput)

        let expected: [[String: Any]] = [
            [
                "role": "system",
                "content": "You are a helpful assistant.",
            ],
            [
                "role": "user",
                "content": "What is MLX?",
            ],
            [
                "role": "assistant",
                "content": "MLX is a machine learning framework for Apple silicon.",
            ],
            [
                "role": "user",
                "content": "Tell me more.",
            ],
        ]

        assertEqual(expected, messages)
    }

    // MARK: - Messages with Images

    public func testSingleImageMessage() {
        let chat: [Chat.Message] = [
            .user(
                "What is this?",
                images: [
                    .url(URL(string: "https://example.com/image.png")!)
                ]
            )
        ]

        let userInput = UserInput(chat: chat)
        let messages = PixtralMessageGenerator().generate(from: userInput)

        // Expected format: content becomes an array with text chunk and image chunk
        let expected: [[String: Any]] = [
            [
                "role": "user",
                "content": [
                    [
                        "type": "text",
                        "text": "What is this?",
                    ],
                    [
                        "type": "image"
                    ],
                ] as [[String: Any]]
            ]
        ]

        assertEqual(expected, messages)
    }

    public func testMultipleImagesMessage() {
        let chat: [Chat.Message] = [
            .user(
                "Compare these images.",
                images: [
                    .url(URL(string: "https://example.com/image1.png")!),
                    .url(URL(string: "https://example.com/image2.png")!),
                ]
            )
        ]

        let userInput = UserInput(chat: chat)
        let messages = PixtralMessageGenerator().generate(from: userInput)

        let expected: [[String: Any]] = [
            [
                "role": "user",
                "content": [
                    [
                        "type": "text",
                        "text": "Compare these images.",
                    ],
                    [
                        "type": "image"
                    ],
                    [
                        "type": "image"
                    ],
                ] as [[String: Any]]
            ]
        ]

        assertEqual(expected, messages)
    }

    public func testEmptyTextWithImage() {
        // Test case where user sends only an image with no text
        let chat: [Chat.Message] = [
            .user(
                "",  // Empty text
                images: [
                    .url(URL(string: "https://example.com/image.png")!)
                ]
            )
        ]

        let userInput = UserInput(chat: chat)
        let messages = PixtralMessageGenerator().generate(from: userInput)

        // When text is empty, we still include it as a text chunk
        let expected: [[String: Any]] = [
            [
                "role": "user",
                "content": [
                    [
                        "type": "text",
                        "text": "",
                    ],
                    [
                        "type": "image"
                    ],
                ] as [[String: Any]]
            ]
        ]

        assertEqual(expected, messages)
    }

    public func testMixedConversationWithImages() {
        let chat: [Chat.Message] = [
            .system("You are a vision assistant."),
            .user("Describe this image.", images: [.url(URL(string: "https://example.com/img1.png")!)]),
            .assistant("I see a beautiful landscape."),
            .user("What about this one?", images: [.url(URL(string: "https://example.com/img2.png")!)]),
        ]

        let userInput = UserInput(chat: chat)
        let messages = PixtralMessageGenerator().generate(from: userInput)

        let expected: [[String: Any]] = [
            [
                "role": "system",
                "content": "You are a vision assistant.",
            ],
            [
                "role": "user",
                "content": [
                    ["type": "text", "text": "Describe this image."],
                    ["type": "image"],
                ] as [[String: Any]]
            ],
            [
                "role": "assistant",
                "content": "I see a beautiful landscape.",
            ],
            [
                "role": "user",
                "content": [
                    ["type": "text", "text": "What about this one?"],
                    ["type": "image"],
                ] as [[String: Any]]
            ],
        ]

        assertEqual(expected, messages)
    }

    // MARK: - Direct Text Prompt

    public func testDirectTextPrompt() {
        // Test UserInput.Prompt.text case
        let userInput = UserInput(prompt: .text("Hello, world!"))
        let messages = PixtralMessageGenerator().generate(from: userInput)

        let expected: [[String: Any]] = [
            [
                "role": "user",
                "content": "Hello, world!",
            ]
        ]

        assertEqual(expected, messages)
    }

    // MARK: - Direct Messages Format

    public func testDirectMessagesFormat() {
        // Test UserInput.Prompt.messages case (pre-formatted messages)
        let preformattedMessages: [[String: Any]] = [
            [
                "role": "system",
                "content": "Custom system prompt.",
            ],
            [
                "role": "user",
                "content": [
                    ["type": "text", "text": "Analyze this."],
                    ["type": "image"],
                ] as [[String: Any]]
            ],
        ]

        let userInput = UserInput(prompt: .messages(preformattedMessages))
        let messages = PixtralMessageGenerator().generate(from: userInput)

        // Should pass through unchanged
        assertEqual(preformattedMessages, messages)
    }

    // MARK: - Role Validation

    public func testAllRoles() {
        let chat: [Chat.Message] = [
            .init(role: .system, content: "System message"),
            .init(role: .user, content: "User message"),
            .init(role: .assistant, content: "Assistant message"),
        ]

        let userInput = UserInput(chat: chat)
        let messages = PixtralMessageGenerator().generate(from: userInput)

        XCTAssertEqual(messages.count, 3)
        XCTAssertEqual((messages[0] as? [String: Any])?["role"] as? String, "system")
        XCTAssertEqual((messages[1] as? [String: Any])?["role"] as? String, "user")
        XCTAssertEqual((messages[2] as? [String: Any])?["role"] as? String, "assistant")
    }

    // MARK: - mistral-common Compatibility Checks

    /// Verify that the message structure matches mistral-common's UserMessage format
    /// Reference: UserMessage.content can be str | list[UserContentChunk]
    public func testMistralCommonUserMessageFormat() {
        // Test both simple string content and multi-part content
        let simpleChat: [Chat.Message] = [.user("Simple text")]
        let simpleInput = UserInput(chat: simpleChat)
        let simpleMessages = PixtralMessageGenerator().generate(from: simpleInput)

        // Simple case: content is string
        if let firstMessage = simpleMessages.first as? [String: Any] {
            XCTAssertTrue(firstMessage["content"] is String)
        } else {
            XCTFail("Expected dictionary message")
        }

        // Multi-part case: content is array
        let multipartChat: [Chat.Message] = [
            .user("Text with image", images: [.url(URL(string: "https://example.com/img.png")!)])
        ]
        let multipartInput = UserInput(chat: multipartChat)
        let multipartMessages = PixtralMessageGenerator().generate(from: multipartInput)

        if let firstMessage = multipartMessages.first as? [String: Any] {
            XCTAssertTrue(firstMessage["content"] is [[String: Any]])

            if let content = firstMessage["content"] as? [[String: Any]] {
                // Should have text chunk and image chunk
                XCTAssertEqual(content.count, 2)
                XCTAssertEqual(content[0]["type"] as? String, "text")
                XCTAssertEqual(content[1]["type"] as? String, "image")
            } else {
                XCTFail("Expected array content")
            }
        } else {
            XCTFail("Expected dictionary message")
        }
    }

    /// Verify chunk structure matches mistral-common's TextChunk/ImageChunk format
    /// Reference: TextChunk has {type: "text", text: str}, ImageChunk has {type: "image"}
    public func testMistralCommonChunkFormat() {
        let chat: [Chat.Message] = [
            .user("Describe this", images: [.url(URL(string: "https://example.com/img.png")!)])
        ]

        let userInput = UserInput(chat: chat)
        let messages = PixtralMessageGenerator().generate(from: userInput)

        guard let message = messages.first as? [String: Any],
              let content = message["content"] as? [[String: Any]] else {
            XCTFail("Expected message with array content")
            return
        }

        // TextChunk format
        let textChunk = content[0]
        XCTAssertEqual(textChunk["type"] as? String, "text")
        XCTAssertNotNil(textChunk["text"])
        XCTAssertEqual(textChunk.keys.count, 2, "TextChunk should have exactly 2 keys: type and text")

        // ImageChunk format
        let imageChunk = content[1]
        XCTAssertEqual(imageChunk["type"] as? String, "image")
        XCTAssertEqual(imageChunk.keys.count, 1, "ImageChunk should have exactly 1 key: type")
    }
}
